"""added is_active column in UserModel.

Revision ID: 82a11b3c776f
Revises: e6a071cac56e
Create Date: 2026-01-19 23:44:34.532271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a11b3c776f'
down_revision: Union[str, Sequence[str], None] = 'e6a071cac56e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserAccount', sa.Column('is_active', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserAccount', 'is_active')
    # ### end Alembic commands ###
