"""changed password column to string.

Revision ID: e6a071cac56e
Revises: 
Create Date: 2026-01-16 20:48:58.005080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6a071cac56e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ChatDetails', ['chat_id'])
    op.alter_column('UserAccount', 'pswd',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserAccount', 'pswd',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.drop_constraint(None, 'ChatDetails', type_='unique')
    # ### end Alembic commands ###
